---
name: silverstripe-staging-warning
---
SilverStripe\Admin\LeftAndMain:
  extensions:
    - WeDevelop\StagingWarning\Extensions\LeftAndMainWarningExtension

Silverstripe\SiteConfig\SiteConfig:
  extensions:
    - WeDevelop\StagingWarning\Extensions\SiteConfigExtension
