---
name: silverstripe-staging-warning
Except:
  environment: 'live'
---
Silverstripe\SiteConfig\SiteConfig:
  extensions:
    - WeDevelop\StagingWarning\Extensions\SiteConfigExtension

SilverStripe\Admin\LeftAndMain:
  extensions:
    LeftAndMainWarningExtension: WeDevelop\StagingWarning\Extensions\LeftAndMainWarningExtension
  extra_requirements_css:
    - 'wedevelopnl/silverstripe-staging-warning:client/dist/styles/bundle.css'